services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      NODE_ID: 1
      NODE_PORT: 8001
      SELF_URL: http://node1:8001
      CLUSTER_NODES: http://node1:8001,http://node2:8001,http://node3:8001
      REDIS_URL: redis://redis:6379/0
      ELECTION_TIMEOUT_MIN: 1200
      ELECTION_TIMEOUT_MAX: 2200
      HEARTBEAT_INTERVAL: 400
    depends_on: [redis]
    ports: ["8001:8001"]      # <— host 8001 → container 8001

  node2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      NODE_ID: 2
      NODE_PORT: 8001
      SELF_URL: http://node2:8001 
      CLUSTER_NODES: http://node1:8001,http://node2:8001,http://node3:8001
      REDIS_URL: redis://redis:6379/0
      ELECTION_TIMEOUT_MIN: 1200
      ELECTION_TIMEOUT_MAX: 2200
      HEARTBEAT_INTERVAL: 400
    depends_on: [redis]
    ports: ["8002:8001"]        # <— host 8002 → container 8001

  node3:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    environment:
      NODE_ID: 3
      NODE_PORT: 8001
      SELF_URL: http://node3:8001 
      CLUSTER_NODES: http://node1:8001,http://node2:8001,http://node3:8001
      REDIS_URL: redis://redis:6379/0
      ELECTION_TIMEOUT_MIN: 1200
      ELECTION_TIMEOUT_MAX: 2200
      HEARTBEAT_INTERVAL: 400
    depends_on: [redis]
    ports: ["8003:8001"]        # <— host 8003 → container 8001
